name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: '*'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: setup
        run: sudo ./ci/setup_clang.sh
      - name: format
        run: ./ci/format_check.sh
      - name: lint
        run: ./ci/linter_check.sh
      - name: test
        run: make test
